//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQTOSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Category { get; set; }
        public Nullable<double> P_Price { get; set; }
        public Nullable<int> P_Quantity { get; set; }
    }
}
